### ISSUE TITLE
"Unfork" the BitcoinCashFlow repo

### ISSUE THREAD

**Issue by slashrsm** [BitcoinDB/BitcoinCashFlow#34]
Our project is still marked as the fork of bitcoincashjs/bitcoincashjs. This can have unwanted consequences such as unintentionally opening the pull requests in the wrong project. 

It seems that it is possible [to drop the connection by contacting the GitHub support staff](https://stackoverflow.com/a/29326840/1863211).

**Comment by ClemensLey** [comment]
I contacted Github support

**Comment by slashrsm** [comment]
"Forked from ..." is gone from the header.
